version: '3.3'

services:
  user-db:
    image: postgres:13-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  restaurant-db:
    image: postgres:13-alpine
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurantdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  order-db:
    image: postgres:13-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"