spring.application.name=user-service
# Server
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://192.168.99.100:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=password

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.fooddelivery.userservice=DEBUG